name: testing for PR

on:
  pull_request:

jobs:
  test:
    name: testing PR build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Execute Tests
        run: make test-coverage
